repos:
  - repo: https://github.com/standard/standard
    rev: v16.0.3
    hooks:
      - id: standard
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.0.11
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        config: .ansible-lint.yml
