name: Auto Comment
on: pull_request

jobs:
  local-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            `./scripts/checkout.sh $GITHUB_REPOSITORY` - type in repo root to checkout this change locally
            
