name: Linter
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
